apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-monitor-sites
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: monitor-sites
            image: azurenapratica/jobmonitorsites:1.0
            env:
            - name: BaseMonitoramento
              value: DefaultEndpointsProtocol=https;AccountName=groffemonitorstr2;AccountKey=k4r2pE1kIo8nEEalucH4z/hB0KS3vbEfnqJmkYhF771kCgG6WSEWbNpzInc3TaSkS6WRCL0IlOkg/FGZ8GqnGA==;EndpointSuffix=core.windows.net
          restartPolicy: OnFailure